module.exports = Common.Utils.Mapper([
	{ src: 'Active', dest: 'active', default: true },
	{ src: 'Name', dest: 'name', default: 'Unknown' },
	// { src: 'OrganisationNumber', dest: 'info.orgNumber' },
	{ src: 'VATNumber', dest: 'info.vatNumber' },
	// { src: 'TermsOfPayment', dest: 'info.termsOfPayment', default: '30' },
	{ src: 'ID', dest: 'meta.customerNumber' },
	// { src: 'YourRef', dest: 'contact.internal.name', default: 'Unknown' },
	{ src: 'Phone', dest: 'contact.internal.phone' },
	// { src: 'contact name', dest: 'contact.general.name' },
	{ src: 'Email', dest: 'contact.general.email' },
	{ src: 'AddressLine1', dest: 'contact.general.street' },
	{ src: 'AddressLine2', dest: 'contact.general.street2' },
	{ src: 'City', dest: 'contact.general.city' },
	// { src: 'contact zipcode', dest: 'contact.general.zipcode' },
	// { src: 'contact phone', dest: 'contact.general.phone' },
	{ src: 'Country', dest: 'contact.general.country' },
	// { src: 'DeliveryName', dest: 'contact.shipping.name' },
	// 	{ src: 'Email', dest: 'contact.shipping.email' },
	// { src: 'DeliveryAddress1', dest: 'contact.shipping.street' },
	// { src: 'DeliveryAddress2', dest: 'contact.shipping.street2' },
	// { src: 'DeliveryCity', dest: 'contact.shipping.city' },
	// { src: 'DeliveryZipCode', dest: 'contact.shipping.zipcode' },
	// { src: 'DeliveryPhone1', dest: 'contact.shipping.phone' },
	// { src: 'DeliveryCountry', dest: 'contact.shipping.country' },
	// 	{ src: 'EmailInvoice', dest: 'contact.billing.email' },
]);
