module.exports = Common.Utils.Mapper([
	{ src: 'Active', dest: 'active', default: true },
	{ src: 'Name', dest: 'name', default: 'Unknown' },
	// { src: 'OrganisationNumber', dest: 'info.orgNumber' },
	{ src: 'VATNumber', dest: 'info.vatNumber' },
	// { src: 'TermsOfPayment', dest: 'info.termsOfPayment', default: '30' },
	{ src: 'Bank', dest: 'info.accounts[0].bank' },
	{ src: 'BankAccount', dest: 'info.accounts[0].bankAccountNumber' },
	// { src: 'ClearingNumber', dest: 'info.accounts[0].clearingNumber' },
	// { src: 'BG', dest: 'info.accounts[0].BG' },
	// { src: 'PG', dest: 'info.accounts[0].PG' },
	{ src: 'BICCode', dest: 'info.accounts[0].bic' },
	{ src: 'IBAN', dest: 'info.accounts[0].iban' },
	{ src: 'ID', dest: 'meta.supplierNumber' },
	// { src: 'OurReference', dest: 'contact.internal.name' },
	{ src: 'Phone', dest: 'contact.internal.phone' },
	{ src: 'Email', dest: 'contact.general.email' },
	{ src: 'AddressLine1', dest: 'contact.general.street' },
	{ src: 'AddressLine2', dest: 'contact.general.street2' },
	{ src: 'City', dest: 'contact.general.city' },
	{ src: 'Country', dest: 'contact.general.country' },
	// { src: 'DeliveryName', dest: 'contact.shipping.name' },
	{ src: 'Email', dest: 'contact.shipping.email' },
	// { src: 'DeliveryAddress1', dest: 'contact.shipping.street' },
	// { src: 'DeliveryAddress2', dest: 'contact.shipping.street2' },
	// { src: 'DeliveryCity', dest: 'contact.shipping.city' },
	// { src: 'DeliveryZipCode', dest: 'contact.shipping.zipcode' },
	// { src: 'DeliveryPhone1', dest: 'contact.shipping.phone' },
	// { src: 'DeliveryCountry', dest: 'contact.shipping.country' },
	// { src: 'EmailInvoice', dest: 'contact.billing.email' },
]);
