module.exports = Common.Utils.Mapper([
// 	{ src: 'TermsOfPayment NumberOfDays', dest: 'info.termsOfPayment', default: '30' },
	{ src: 'IsActive', dest: 'active', default: true },
	{ src: 'name', dest: 'name', default: 'Unknown' },
	{ src: 'company_name', dest: 'info.orgNumber' },
	{ src: 'vat', dest: 'info.vatNumber' },
	{ src: 'id', dest: 'meta.customerNumber' },
	{ src: 'phone', dest: 'contact.internal.phone' },
// 	{ src: 'ContactPersonName', dest: 'contact.general.name' },
	{ src: 'email', dest: 'contact.general.email' },
// 	{ src: 'InvoiceAddress1', dest: 'contact.general.street' },
// 	{ src: 'InvoiceAddress2', dest: 'contact.general.street2' },
// 	{ src: 'InvoiceCity', dest: 'contact.general.city' },
// 	{ src: 'InvoicePostalCode', dest: 'contact.general.zipcode' },
// 	{ src: 'ContactPersonPhone', dest: 'contact.general.phone' },
// 	{ src: 'InvoiceCountryCode', dest: 'contact.general.country' },
// 	{ src: 'DeliveryCustomerName', dest: 'contact.shipping.name' },
// 	{ src: 'EmailAddress', dest: 'contact.shipping.email' },
// 	{ src: 'DeliveryAddress1', dest: 'contact.shipping.street' },
// 	{ src: 'DeliveryAddress2', dest: 'contact.shipping.street2' },
// 	{ src: 'DeliveryCity', dest: 'contact.shipping.city' },
// 	{ src: 'DeliveryPostalCode', dest: 'contact.shipping.zipcode' },
// 	{ src: 'DeliveryCountryCode', dest: 'contact.shipping.country' },
]);

