module.exports = Common.Utils.Mapper([
	{ src: 'IsActive', dest: 'active', default: true },
	{ src: 'name', dest: 'name', default: 'Unknown' },
	// { src: 'TermsOfPaymentId', dest: 'info.termsOfPayment', default: '30' },
	{ src: 'bank_ids[0]', dest: 'info.accounts[0].bankAccountNumber' },
	// 	{ src: 'BankBic', dest: 'info.accounts[0].bic' },
	// 	{ src: 'BankIban', dest: 'info.accounts[0].iban' },
	{ src: 'id', dest: 'meta.supplierNumber' },
	{ src: 'email', dest: 'contact.general.email' },
	{ src: 'contact_address', dest: 'contact.general.street' },
	// 	{ src: 'Address2', dest: 'contact.general.street2' },
	{ src: 'city', dest: 'contact.general.city' },
	// 	{ src: 'EmailAddress', dest: 'contact.shipping.email' },
	// 	{ src: 'BankName', dest: 'info.accounts[0].bank' },
	// 	{ src: 'ContactPersonName', dest: 'contact.internal.name' },
	// 	{ src: 'CountryCode', dest: 'contact.general.country' },
	// 	{ src: 'ContactPersonName', dest: 'contact.shipping.name' },
	{ src: 'company_id[1]', dest: 'info.orgNumber' },
	{ src: 'vat', dest: 'info.vatNumber' },
	//	{ src: 'ClearingNumber', dest: 'info.accounts[0].clearingNumber' },
	// 	{ src: 'BG', dest: 'info.accounts[0].BG' },
	// 	{ src: 'PG', dest: 'info.accounts[0].PG' },
	{ src: 'phone', dest: 'contact.internal.phone' },
	// 	{ src: 'DeliveryAddress1', dest: 'contact.shipping.street' },
	// 	{ src: 'DeliveryAddress2', dest: 'contact.shipping.street2' },
	// 	{ src: 'DeliveryCity', dest: 'contact.shipping.city' },
	// 	{ src: 'DeliveryZipCode', dest: 'contact.shipping.zipcode' },
	// 	{ src: 'DeliveryPhone1', dest: 'contact.shipping.phone' },
	// 	{ src: 'DeliveryCountry', dest: 'contact.shipping.country' },
	// 	{ src: 'EmailInvoice', dest: 'contact.billing.email' },

]);
